### ISSUE TITLE
공유하기 API 알아보기

### ISSUE THREAD

**Issue by rheech22** [twinstae/coaching-sospeso#21]
소스페소 공유하기에 사용할만한 API 조사

**Comment by twinstae** [comment]
https://developer.mozilla.org/ko/docs/Web/API/Navigator/share

**Comment by rheech22** [comment]
share api를 사용해 보았는데 모바일과 달리 데스크탑 브라우저에서는 공유 다이얼로그가 다소 빈약하네요. `확장 프로그램 편집...`을 통해 메뉴 구성을 바꿔보려 했지만 제대로 바뀌지 않았어요. (사용자가 직접 설정할 수 있더라도 이대로 제공하긴 어렵겠죠 ㅎㅎ)
<img width="248" alt="스크린샷 2024-11-05 오후 1 58 39" src="https://github.com/user-attachments/assets/fadb2b8f-e819-4656-b718-b092c088acdd">

모바일에서만 share api를 사용하고 데스크탑 환경에서는 커스텀 다이얼로그나 버튼 목록(copy, 주요 SNS?)을 보여주는 것이 좋을까요?

**Comment by twinstae** [comment]
저는 데스크탑이랑 모바일이랑 둘 다 일단 share api를 쓰고, 말씀하신 것처럼 popover 로 더 다양한 메뉴를 보여주는 걸 고도화로 가져가면 어떨까 싶네요. ;)

**Comment by rheech22** [comment]
- 기본 메뉴에 복사하기 항목조차 없는 것이 마음에 조금 걸리는데 괜찮을까요?
   (아니면 데스크탑인 경우 기존 클립보드 복사 기능을 그대로 두는 것이 좋을까요..?)
- 만약 복사하기 대신 share api를 붙인다면 https://github.com/twinstae/coaching-sospeso/issues/22 는 진행하지 않아도 되겠네요 !

구현 방향 정리되면 작업 진행하겠습니다 ㅎㅎ

**Comment by twinstae** [comment]
알아보니 share api 자체가 아직 실험적인 기능이라 브라우저 지원이 잘 안 되네요.

;) 오히려  처음 이야기한 것처럼 복사되고 + toast 뜨는 정도로만 구현을 해보시죠. #22

**Comment by twinstae** [comment]
확인하시면 이 이슈는 닫아도 되겠습니다.

**Comment by rheech22** [comment]
넵 나중에 고도화 단계에서 한번 같이 고민해봐도 좋을 것 같습니다 ㅎㅎ
