### ISSUE TITLE
Oauth 인증 구현

### ISSUE THREAD

**Issue by twinstae** [twinstae/coaching-sospeso#29]
회원가입 로그인 시에 인증을 구현해줘야 합니다.

Lucia
-> 프레임워크나 db 종속성이 없는 간단한 라이브러리 v3 는 deprecated 되었지만 직접 구현에 참고해도 되고 그냥 써도 큰 문제는 없을듯 합니다.
https://v2.lucia-auth.com/getting-started/

Supabase auth
Netlify GoTrue 기반으로 supabase 의 클라우드에서 제공하는 인증. Supabase 종속이 가장 신경 쓰이는...
https://supabase.com/docs/guides/auth

**Comment by taehee-sp** [comment]
https://www.better-auth.com/
열심히 개발 중인 친구인 모양...

https://authjs.dev/
astro가 추천함

**Comment by twinstae** [comment]
일단 better auth 로 구현했고 구글과 깃허브는 잘 되는데... 트위터는 안 되서 원 레포에 이슈를 올려뒀습니다. 별도 이슈로 분할하고 닫겠습니다.
